### ISSUE TITLE
Issue with distanzring.3mf

### ISSUE THREAD

**Issue by ctobio** [bastelgarage/dual-led-ring-watch#2]
distanzring.3mf does not load up in any software, including PrusaSlicer, and seems truncated at 1KB. I suspect the file is malformed.

**Comment by t3chn0m4g3** [comment]
same issue here, @AlfMueller can you push the `distanzring.3mf` again? really looking forward to make this 😁
thank you!

**Comment by jtrauger** [comment]
agreed, something wrong with file

**Comment by AlfMueller** [comment]
I add a new Version V2

**Comment by t3chn0m4g3** [comment]
@AlfMueller Thank you!
